name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set build image var
        run: echo "ImageVersion=$ImageVersion" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Building
        run: |
          ./node_modules/.bin/zx ./bin/serve.mjs
      - name: Deploy to Pages
        if: github.event_name == 'schedule'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./serve/
          cname: cdn.advtr.co.uk
          force_orphan: true
      - name: Tell Honeybadger.io
        if: github.event_name == 'schedule'
        env:
          HONEYBADGER_TOKEN: ${{ secrets.HONEYBADGER_TOKEN }}
        run: |
          curl https://api.honeybadger.io/v1/check_in/${HONEYBADGER_TOKEN}
      - uses: actions/upload-artifact@v2
        if: github.event_name != 'schedule'
        with:
          name: site
          path: ./serve/*

on:
  push:
  repository_dispatch:
    types:
      - cronjob
  schedule:
    - cron:  '0 2 * * *'
      branches:
        - master
